global:
  sendAnonymousUsage: true

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
  consulCatalog:
    refreshInterval: 30s
    connectAware: true
    serviceName: "traefik"
    endpoint:
      address: 	172.19.0.4:8500
      datacenter: dc
  file:
    filename: /etc/traefik/config.yml
    watch: true
   
log:    
  level: INFO
  format: common
  
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
