version: '3.3'

services:
  encrypter:
    image: encrypter-ms:consul
    environment:
      - CONSUL_HOST=172.19.0.4
    networks:
      - red
    restart: always
    ports:
      - 5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.encrypter.rule=Host(`encrypter.encrypteam.localhost`)"
      - "traefik.http.routers.encrypter.tls=true"
      - "traefik.http.services.encrypter.loadbalancer.server.port=5000"

networks:
  red:
    external: true
