version: '3.3'
services:
  consul:
    image: consul:latest
    networks:
       red:
         ipv4_address: 172.19.0.4
    ports:
      - "8500:8500"
      - "8300:8300"
      - "8600:8600/udp"
    volumes:
      - ./config:/consul/config
      - ./data:/consul/data:rw
      - ./ca:/consul/ca
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.consul.rule=Host(`consul.encrypteam.localhost`)"
      - "traefik.http.routers.consul.tls=true"
      - "traefik.http.services.consul.loadbalancer.server.port=8500"
    command: agent -bind 0.0.0.0 -disable-host-node-id=true
networks:
  red:
    external: true
