version: "3.3"
services:
  elasticsearch:
    image: elasticsearch:7.14.2
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTIC_PASSWORD=elastic
      - ES_JAVA_OPTS=-Xms960m -Xmx3840m
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data/:rw
    networks:
      - red
  logstash:
    image: logstash:7.14.2
    ports:
      - "5044:5044"
      - "5059:5000/tcp"
      - "5059:5000/udp"
      - "9600:9600"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline.yml
    depends_on:
      - elasticsearch
    networks:
      - red
  kibana:
    image: kibana:7.14.2
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - red
networks:
  red:
    external: true