global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'encrypter'
    scrape_interval: 15s
    scheme: http
    static_configs:
      - targets: [ 'encrypter:5000' ]

  - job_name: 'user'
    scrape_interval: 5s
    scheme: http
    static_configs:
      - targets: ['userflask:5000']

