version: '3.3'

services:
  prometheus:
    networks:
      - red
    image: prom/prometheus
    ports:
      - 9090:9090
 #   labels:
 #     - "traefik.enable=true"
  #    - "traefik.http.routers.prometheus.rule=Host(`prometheus.encrypteam.localhost`)"
   #   - "traefik.http.routers.prometheus.tls=true"
    #  - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
    volumes:
      - ./config/:/etc/prometheus/:rw
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    networks:
      - red
    image: grafana/grafana
    ports:
      - 3000:3000
    #labels:
     # - "traefik.enable=true"
      #- "traefik.http.routers.grafana.rule=Host(`grafana.encrypteam.localhost`)"
      #- "traefik.http.routers.grafana.tls=true"
      #- "traefik.http.services.grafana.loadbalancer.server.port=3000"
    volumes:
      - ./datasource.yml:/etc/grafana/provisioning/datasource/datasource.yml
    depends_on:
      - prometheus

networks:
  red:
    external: true
